name: platonus_quiz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  docx_to_text: ^1.0.1
  shared_preferences: ^2.3.2
  file_picker: ^9.0.2
  path: ^1.9.0
  flutter_bloc: ^9.1.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  skeletonizer: ^1.4.2
  scrollable_positioned_list: ^0.3.8
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
